### ISSUE TITLE
SecurityContext class is deprecated 

### ISSUE THREAD

**Issue by pinoniq** [wanjee/ShuweeAdminBundle#11]
The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0

We should use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead. 

Same goes for the The Symfony\Component\Security\Core\SecurityContextInterface

**Comment by wanjee** [comment]
See #15
