### ISSUE TITLE
Fix Open Sans font-family issue

### ISSUE THREAD

**Issue by wanjee** [wanjee/ShuweeAdminBundle#20]
_global.scss declares body style as "font-family: 'Open Sans', sans-serif;" result is ugly on some computers.

It seems the font used is sometimes "Open Sans Bold" instead of "Open Sans"

**Comment by pinoniq** [comment]
We could also add the Open sans google font tag to the code?

**Comment by wanjee** [comment]
It already is using @import url(http://fonts.googleapis.com/css?family=Open+Sans); in _global.scss

**Comment by pinoniq** [comment]
URL used is http. so it will be blocked when using https?

**Comment by wanjee** [comment]
Was a local problem due to partially installed font set (only "Open Sans bold" font was installed, browsers were matching "Open Sans" with it and use it instead of the regular that should have been fetched from google fonts.

Remaining issue to fix is : avoid the use of URL scheme when importing font-face.
