### ISSUE TITLE
Typo on ConfigureMenuItem method

### ISSUE THREAD

**Issue by Dromadoros** [wanjee/ShuweeAdminBundle#28]
You use addChild method to a non-existant object :

$menu = $event->getMenu();

$contentMenuItem->addChild('Menu item #1', array('route' => 'admin_route_1'));
$contentMenuItem->addChild('Menu item #2', array('route' => 'admin_route_2'));

it works with this :

$menu->addChild('Menu item #1', array('route' => 'admin_route_1'));
$menu->addChild('Menu item #2', array('route' => 'admin_route_2'));

**Comment by wanjee** [comment]
Thanks !
